# Uncomment the next line to define a global platform for your project
platform :ios, '11.2'

target 'Pachikin' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Pachikin
  pod 'GoogleMaps'

  target 'PachikinTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PachikinUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
